### ISSUE TITLE
Dependency update required for the Go extension

### ISSUE THREAD

**Issue by stamblerre** [stephnr/vscode-go-coverage-viewer#3]
Hello, the [ms-vscode.Go](https://github.com/microsoft/vscode-go) extension has migrated to [golang.Go](https://marketplace.visualstudio.com/items?itemName=golang.Go) ([details](https://github.com/microsoft/vscode-go/issues/3247), [blog post](https://golang.blog/vscode-go)). Please update your dependency on this extension to "golang.Go".

**Comment by acgreek** [comment]
I filed a pull request to correct this https://github.com/stephnr/vscode-go-coverage-viewer/pull/4
but this repo maybe dead given that stephnr hasn't updated it in 2 years.

**Comment by sorenh** [comment]
I've forked this project and published an updated extension where this is fixed.

https://marketplace.visualstudio.com/items?itemName=soren.go-coverage-viewer

Enjoy.

**Comment by RobotSail** [comment]
I'm still having this problem, thanks for fixing that up @sorenisanerd !

**Comment by robert-7** [comment]
Thank you. This is a great solution. It would be nice if there was a way to take Defaltd (defaltd.go-coverage-viewer) off the VS Code Marketplace. It shows up first on my search, even though it has less reviews.

And I can't comment this on https://github.com/golang/vscode-go/issues/2201 🙄
